# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-23.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx source/"

sphinx:
  builder: html
  configuration: source/conf.py

# Optionally declare the Python requirements required to build your docs
conda:
  environment: environment.yml
