# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-26.04
  tools:
    python: "miniforge3-25.11"
  jobs:
    build:
      html:
        - "python -m jupyter_book build --site --strict --ci"
        - "cp -a _build/html \"$READTHEDOCS_OUTPUT/\""

# Optionally declare the Python requirements required to build your docs
conda:
  environment: environment.yml
