name: seismology101
channels:
    - conda-forge
    - nodefaults
dependencies:
    - python=3.9
    - pip
    - sphinx
    - sphinx-copybutton
    - sphinx-panels
    - sphinx_rtd_theme
    - myst-nb
    - obspy=1.2.2
    - pip:
      - sphinx-cjkspace
