# JupyterBook settings
# Learn more at https://jupyterbook.org/en/stable/customize/config.html

# Book settings
title: "地震“学”科研入门教程"
author: seismo-learn
copyright : "2020–2025"

# Execution settings
execute:
  execute_notebooks: auto
  timeout: 300

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution
    - tasklist
  myst_substitutions:
    田冬冬: "[田冬冬](https://me.seisman.info/)"
    姚家园: "[姚家园](https://github.com/core-man)"
    王亮: "[王亮](https://github.com/wangliang1989)"
    赵志远: "[赵志远](https://github.com/zhaozhiyuan1989)"
    何星辰: "[何星辰](https://github.com/Chuan1937)"

# HTML-specific settings
html:
  favicon: favicon.ico
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

# Repository settings
repository:
  url: https://github.com/seismo-learn/seismology101
  path_to_book: source
  branch: main

# Citation settings
bibtex_bibfiles:
  - references.bib

# Advanced sphinx settings
sphinx:
  config:
    intersphinx_mapping:
      seis:
        - https://seismo-learn.org/seismology/
        - null
      seis101:
        - https://seismo-learn.org/seismology101/
        - null
      software:
        - https://seismo-learn.org/software/
        - null
      matplotlib:
        - https://matplotlib.org/stable/
        - null
      numpy:
        - https://numpy.org/doc/stable/
        - null
      obspy:
        - https://docs.obspy.org/
        - null
    copybutton_prompt_text: '>>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}:'
    copybutton_prompt_is_regexp: true
    copybutton_only_copy_prompt_lines: true
    copybutton_remove_prompts: true
    bibtex_default_style: plain
    bibtex_reference_style: super
