# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "地震学入门教程"
author = "seismo-learn"
copyright = f"2020, {author}."


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.githubpages",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "zh_CN"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------
import sphinx_rtd_theme

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_extra_path = []
html_last_updated_fmt = "%Y年%m月%d日"
html_title = project

html_context = {
    "favicon" : "favicon.ico",
    "display_github": True,
    "github_user": "seismo-learn",
    "github_repo": "seismology101",
    "github_version": "main",
    "conf_py_path": "/source/",
    "theme_vcs_pageview_mode": "blob",
    "menu_links": [
        (
            '<i class="fa fa-github fa-fw"></i> 网站源码',
            "https://github.com/seismo-learn/seismology101",
        ),
        (
            '<i class="fa fa-edit fa-fw"></i> 贡献指南',
            "https://github.com/seismo-learn/seismology101/blob/main/CONTRIBUTING.md",
        ),
        (
            '<i class="fa fa-comments fa-fw"></i> 参与讨论',
            "https://github.com/seismo-learn/seismology101/discussions",
        ),
    ],
}