#
# Build and deploy the documentation
#
name: Build and Deploy

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run weekly at 00:00 on Sunday
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_URL: /seismology101
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v3.0.0
        with:
          environment-file: environment.yml
          cache-downloads: false
          cache-environment: true

      - uses: actions/cache@v5
        id: cache
        with:
          path: |
            source/_build/cache/
            source/_build/jupyter_execute/
            ~/.local/share/cartopy/
            ~/.matplotlib/
          key: ${{ runner.os }}-${{ hashFiles('environment.yml', 'source/myst.yml', 'README.md', 'source/**/*.md', 'source/**/*.bib') }}
          restore-keys: ${{ runner.os }}-

      - name: Build documentation
        run: make html

      - name: Deploy documentation
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./source/_build/html
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
